[2023-04-24 17:08:37,315] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.join_all_data manual__2023-04-24T17:08:28.639289+00:00 [queued]>
[2023-04-24 17:08:37,323] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: vic_investigacion_ETL.join_all_data manual__2023-04-24T17:08:28.639289+00:00 [queued]>
[2023-04-24 17:08:37,323] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-04-24 17:08:37,324] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2023-04-24 17:08:37,324] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-04-24 17:08:37,333] {taskinstance.py:1397} INFO - Executing <Task(JoinAllData): join_all_data> on 2023-04-24 17:08:28.639289+00:00
[2023-04-24 17:08:37,339] {standard_task_runner.py:52} INFO - Started process 5232 to run task
[2023-04-24 17:08:37,343] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'vic_investigacion_ETL', 'join_all_data', 'manual__2023-04-24T17:08:28.639289+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/vic_investigacion_dag.py', '--cfg-path', '/tmp/tmpyi67l2v3', '--error-file', '/tmp/tmp_0qkyc9t']
[2023-04-24 17:08:37,345] {standard_task_runner.py:80} INFO - Job 362: Subtask join_all_data
[2023-04-24 17:08:37,419] {task_command.py:371} INFO - Running <TaskInstance: vic_investigacion_ETL.join_all_data manual__2023-04-24T17:08:28.639289+00:00 [running]> on host b136a0a45498
[2023-04-24 17:08:37,477] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=vic_investigacion_ETL
AIRFLOW_CTX_TASK_ID=join_all_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-24T17:08:28.639289+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-24T17:08:28.639289+00:00
[2023-04-24 17:08:37,479] {logging_mixin.py:115} INFO - Joining all data
[2023-04-24 17:08:37,656] {logging_mixin.py:115} INFO - Data joined
[2023-04-24 17:08:37,660] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/join_all_data_operator.py", line 20, in execute
    self.joinScopusData()
  File "/opt/airflow/dags/join_all_data_operator.py", line 36, in joinScopusData
    f.write(join_df)
TypeError: write() argument must be str, not DataFrame
[2023-04-24 17:08:37,675] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=vic_investigacion_ETL, task_id=join_all_data, execution_date=20230424T170828, start_date=20230424T170837, end_date=20230424T170837
[2023-04-24 17:08:37,686] {standard_task_runner.py:97} ERROR - Failed to execute job 362 for task join_all_data (write() argument must be str, not DataFrame; 5232)
[2023-04-24 17:08:37,720] {local_task_job.py:156} INFO - Task exited with return code 1
